### ISSUE TITLE
first accordion open by default

### ISSUE THREAD

**Issue by rzubrycki** [kunukn/react-collapse#1]
Hello, can anyone provide me example how i can implement situation when first accordion is open by default? Much appreciate.

**Comment by kunukn** [comment]
A simple version
https://codepen.io/kunukn/pen/ebdf834db38eda650addad17edcd6b2c?editors=0010

A more complex example
https://codepen.io/kunukn/pen/9fe2f67f13c6602e0fb5b084ec160df5?editors=0010
