### ISSUE TITLE
React 18 support

### ISSUE THREAD

**Issue by jtojnar** [kunukn/react-collapse#43]
Hi, in my limited testing, the `Collapse` seems to work fine with React 18. Do you think it is okay to bump the constraints in peer dependencies?

https://github.com/kunukn/react-collapse/blob/e069b99893ee9ce828f1953571605000f94cf799/package.json#L164

**Comment by jacobclyne** [comment]
@kunukn, any updates on this? I can also confirm that it works fine with React 18.2.0.

**Comment by kunukn** [comment]
Just seeing this now. I will look into it.

**Comment by kunukn** [comment]
It has been updated to support React 18.

[Working Codesandbox demo](https://codesandbox.io/s/react-18-collapse-expand-all-collapse-all-ushjky)
