### ISSUE TITLE
Missing files in package

### ISSUE THREAD

**Issue by caspardue** [kunukn/react-collapse#5]
I have noticed that the following fields in `package.json` point to files that are not being published in the package. 

```
 "module": "dist/Collapse.es.js",
  "cjs": "dist/Collapse.cjs.js",
  "iife": "dist/Collapse.iife.js",
```

Ran into an issue using `babel-eslint` and `eslint-plugin-import`

**Comment by kunukn** [comment]
I will look into it.

**Comment by kunukn** [comment]
I have updated and removed those unused fields.
Version 2.2.8 has been published.

**Comment by caspardue** [comment]
Thanks
