### ISSUE TITLE
Incorrect require structure inside package.json

### ISSUE THREAD

**Issue by desout** [kunukn/react-collapse#51]
It's not possible to require library, because file doesn't exists
<img width="390" alt="image" src="https://github.com/kunukn/react-collapse/assets/35991006/f9d1240a-8cfe-4661-a09c-bc7ccb9bbfed">
Workaround: use deep link instead
<img width="1172" alt="Screenshot 2024-04-05 at 7 57 39 PM" src="https://github.com/kunukn/react-collapse/assets/35991006/2c6e9494-6903-448f-b98f-42f17e621ef5">
<img width="651" alt="image" src="https://github.com/kunukn/react-collapse/assets/35991006/15f96eef-904a-4a11-adc2-6c4d33f9db99">

**Comment by desout** [comment]
<img width="1783" alt="Screenshot 2024-04-05 at 8 04 29 PM" src="https://github.com/kunukn/react-collapse/assets/35991006/98a368ca-e63c-4a28-ac8a-48269d45d930">
not possible use direct link as well :)

**Comment by kunukn** [comment]
I have resolved a couple of wrong file paths. It should be fixed since version 3.0.8

Can you confirm?

**Comment by desout** [comment]
@kunukn Hello, yep, it's works with direct link to dist. Thx
